### ISSUE TITLE
[Question] Improvements over the SourceForge.net version

### ISSUE THREAD

**Issue by pidgeon777** [vinsworldcom/nppTagsView#1]
I noticed your plugin is based on the original sources available here:

https://sourceforge.net/projects/tagsview/

Is a list of the improvements you introduced available somewhere?

Best regards.

**Comment by vinsworldcom** [comment]
No, but from the commits, the only "improvements" were to highlight menu options by letter when the Alt key is pressed and to automatically refresh the list when a file is saved.
