### ISSUE TITLE
[Feature] Toolbar button for disabling caret tracking

### ISSUE THREAD

**Issue by pidgeon777** [vinsworldcom/nppTagsView#2]
When quicking surfing code (for example through NppExec console or other scripts), if the number of lines and detected tags is big, navigation is slowed down. This is due to TagsView automatically refreshing its window by highlighting the tag associated with the currently selected line in NPP editor.

It would be nice to add a button to toggle on/off this caret tracking function (something similar is available on SourceCookifier).

**Comment by vinsworldcom** [comment]
Thanks.  I saw this was abandoned and thought I could use it - I don't.  Unfortunately I'm not maintaining the code since I don't use it in Notepad++ anymore.  Feel free to submit a pull request if you have a solution or fork the repo add yourself.

Cheers.
